openapi: 3.0.2
info:
  title: EPS API
  version: 0.1.1
  termsOfService: 'https://example.com/terms/'
  contact:
    name: Contact Eko
    email: info@eko.co.in
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://ekoin.netlify.app/images/logo.svg'
  description: 
    $ref: description.md

externalDocs:
  description: Checkout the developer portal to read the detailed guides
  url: 'https://developers.eko.in'

tags:
  - name: Agent Management
    description: Onboard your agents/users and manage services for them.
  - name : Customers
    description: Create and verify customers. Perform recurring transactions and add multiple recipients to the same customer.
  - name: Customer KYC
    description: Upgrade customer KYC status and enable higher amount of transactions per month.
  - name: Recipients
    description: Manage recipients for your customers to transfer money to.
  - name: Transaction
    description: Money Transfer APIs.
  - name: Verification APIs
  - name: Banks
    description: Get bank information.
  - name: Token
    description: Accept real-time cash-payment for your digital services.
  - name: Partner Account
    description: Settle your funds into your bank account.
  - name: Fund Settlement
    description: sample description
  - name: AePS Fund Settlement
    description: sample description

servers:
- url: https://staging.eko.in:25004/ekoicici/v1

paths:
  /user/services:
    $ref: ./paths/user@services.yaml

  /user/request/otp:
    $ref: ./paths/user@request@otp.yaml

  /user/verify:
    $ref: ./paths/user@verify.yaml

  /user/onboard:
    $ref: ./paths/user@onboard.yaml

  /user/service/activate:
    $ref: ./paths/user@service@activate.yaml
    
  /user/services/user_code:{user_code}:
    $ref: ./paths/user@services@user_code:{user_code}.yaml

  /onboard:
    $ref: ./paths/onboard.yaml

  /customers/mobile_number:{mobile_number}:
    $ref: ./paths/customers@mobile_number:{mobile_number}.yaml

  /ekoapi/v1/customers/mobile_number:8811990077:
    $ref: ./paths/ekoapi@v1@customers@mobile_number:8811990077.yaml
    
  /ekoapi/v1/customers/product:changename/verification/otp:1633:
    $ref: ./paths/ekoapi@v1@customers@product:changename@verification@otp:1633.yaml
    
  /ekoapi/v1/customers/mobile_number:8811990077/product:changename/otp:
    $ref: ./paths/ekoapi@v1@customers@mobile_number:8811990077@product:changename@otp.yaml
    
  /ekoapi/v1/customers/mobile_number:9899796311:
    put:
      summary: EkoapiV1CustomersMobileNumber9899796311_PUT
      description: Manual KYC using the Aadhaar XML
      operationId: EkoapiV1CustomersMobileNumber9899796311_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/verification/otp:135:
    put:
      summary: EkoapiV1CustomersVerificationOtp135_PUT
      description: Verify customer identity
      operationId: EkoapiV1CustomersVerificationOtp135_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:7065155445/otp:
    post:
      summary: EkoapiV1CustomersMobileNumber7065155445Otp_POST
      description: Resend customer identity verification otp
      operationId: EkoapiV1CustomersMobileNumber7065155445Otp_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/banks:
    get:
      summary: EkoapiV1Banks_GET
      description: Retrieve bank details via bank_code
      operationId: EkoapiV1Banks_GET
      parameters:
        - name: bank_code
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: string
            example: IDFB
        - $ref: "#/components/parameters/initiator_id"
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/banks/bankcode:KKBK/accounts/1711650498:
    post:
      summary: EkoapiV1BanksBankcodeKKBKAccounts1711650498_POST
      description: Account verification
      operationId: EkoapiV1BanksBankcodeKKBKAccounts1711650498_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:8811990077/recipients/acc_ifsc:10037431941_IDFB0041382:
    put:
      summary: EkoapiV1CustomersMobileNumber8811990077RecipientsAccIfsc10037431941IDFB0041382_PUT
      description: Add recipient using account and ifsc
      operationId: EkoapiV1CustomersMobileNumber8811990077RecipientsAccIfsc10037431941IDFB0041382_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:8811990077/recipients/acc_bankcode:1711650498_KKBK:
    put:
      summary: EkoapiV1CustomersMobileNumber8811990077RecipientsAccBankcode1711650498KKBK_PUT
      description: Add recipient using account and bankcode
      operationId: EkoapiV1CustomersMobileNumber8811990077RecipientsAccBankcode1711650498KKBK_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:8800776655/recipients:
    get:
      summary: EkoapiV1CustomersMobileNumber8800776655Recipients_GET
      description: Retrieve all recipients
      operationId: EkoapiV1CustomersMobileNumber8800776655Recipients_GET
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:8811990077/recipients/recipient_id:10016183:
    get:
      summary: EkoapiV1CustomersMobileNumber8811990077RecipientsRecipientId10016183_GET
      description: Get Recipient Detail
      operationId: EkoapiV1CustomersMobileNumber8811990077RecipientsRecipientId10016183_GET
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:8811990077/recipients/recipient_id:10016176:
    delete:
      summary: EkoapiV1CustomersMobileNumber8811990077RecipientsRecipientId10016176_DELETE
      description: Remove recipient
      operationId: EkoapiV1CustomersMobileNumber8811990077RecipientsRecipientId10016176_DELETE
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/split:
    get:
      summary: EkoapiV1TransactionsSplit_GET
      description: 'Split Transaction API '
      operationId: EkoapiV1TransactionsSplit_GET
      parameters:
        - name: customer_id
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int64
            example: 8811990077
        - name: recipient_id
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 10016175
        - name: amount
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 20000
        - name: channel
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 1
        - $ref: "#/components/parameters/initiator_id"
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions:
    post:
      summary: EkoapiV1Transactions_POST
      description: Send money using IMPS channel
      operationId: EkoapiV1Transactions_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/4093/verify:
    put:
      summary: EkoapiV1Transactions4093Verify_PUT
      description: Transaction OTP  Verify API
      operationId: EkoapiV1Transactions4093Verify_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/4091/otp:
    post:
      summary: EkoapiV1Transactions4091Otp_POST
      description: Resend OTP PPI wallet Transaction
      operationId: EkoapiV1Transactions4091Otp_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/15162673:
    get:
      summary: EkoapiV1Transactions15162673_GET
      description: Transaction Inquiry using Eko TID
      operationId: EkoapiV1Transactions15162673_GET
      parameters:
        - $ref: "#/components/parameters/initiator_id"
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/client_ref_id:Settlement0000010:
    get:
      summary: EkoapiV1TransactionsClientRefIdSettlement0000010_GET
      description: Transaction Inquiry using partner reference
      operationId: EkoapiV1TransactionsClientRefIdSettlement0000010_GET
      parameters:
        - $ref: "#/components/parameters/initiator_id"
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/batch/client_ref_id:EKO351551516341814:
    get:
      summary: EkoapiV1TransactionsBatchClientRefIdEKO351551516341814_GET
      description: batch inquiry using client ref
      operationId: EkoapiV1TransactionsBatchClientRefIdEKO351551516341814_GET
      parameters:
        - $ref: "#/components/parameters/initiator_id"
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/15313195/refund:
    post:
      summary: EkoapiV1Transactions15313195Refund_POST
      description: Refund Transaction
      operationId: EkoapiV1Transactions15313195Refund_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/15346925/refund/otp:
    post:
      summary: EkoapiV1Transactions15346925RefundOtp_POST
      description: Resend Refund otp
      operationId: EkoapiV1Transactions15346925RefundOtp_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/pan/verify:
    post:
      summary: EkoapiV1PanVerify_POST
      description: Pan Verification
      operationId: EkoapiV1PanVerify_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:9910028267/balance:
    get:
      summary: EkoapiV1CustomersMobileNumber9910028267Balance_GET
      description: Wallet Balance Inquiry API
      operationId: EkoapiV1CustomersMobileNumber9910028267Balance_GET
      parameters:
        - $ref: "#/components/parameters/initiator_id"
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:9922334455/product:indonepal:
    get:
      summary: EkoapiV1CustomersMobileNumber9922334455ProductIndonepal_GET
      description: Retrieve a customer
      operationId: EkoapiV1CustomersMobileNumber9922334455ProductIndonepal_GET
      parameters:
        - $ref: "#/components/parameters/initiator_id"
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:9922334466/product:indonepal:
    put:
      summary: EkoapiV1CustomersMobileNumber9922334466ProductIndonepal_PUT
      description: Create a customer
      operationId: EkoapiV1CustomersMobileNumber9922334466ProductIndonepal_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/product:indonepal/verification/otp:203:
    put:
      summary: EkoapiV1CustomersProductIndonepalVerificationOtp203_PUT
      description: Verify customer identity
      operationId: EkoapiV1CustomersProductIndonepalVerificationOtp203_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:9922334477/product:indonepal/otp:
    post:
      summary: EkoapiV1CustomersMobileNumber9922334477ProductIndonepalOtp_POST
      description: Resend customer identity verification otp
      operationId: EkoapiV1CustomersMobileNumber9922334477ProductIndonepalOtp_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:9922334466/product:indonepal/recipients:
    put:
      summary: EkoapiV1CustomersMobileNumber9922334466ProductIndonepalRecipients_PUT
      description: Add recipient for cash payout
      operationId: EkoapiV1CustomersMobileNumber9922334466ProductIndonepalRecipients_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:9922334466/product:indonepal/recipients/acc_indonepalbranch:32147368490404004005_11:
    put:
      summary: EkoapiV1CustomersMobileNumber9922334466ProductIndonepalRecipientsAccIndonepalbranch3214736849040400400511_PUT
      description: Add recipient for account deposit
      operationId: EkoapiV1CustomersMobileNumber9922334466ProductIndonepalRecipientsAccIndonepalbranch3214736849040400400511_PUT
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/customers/mobile_number:9922334455/product:indonepal/recipients:
    get:
      summary: EkoapiV1CustomersMobileNumber9922334455ProductIndonepalRecipients_GET
      description: Retrieve all recipients
      operationId: EkoapiV1CustomersMobileNumber9922334455ProductIndonepalRecipients_GET
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/12870517:
    get:
      summary: EkoapiV1Transactions12870517_GET
      description: Transaction inquiry using Eko TID
      operationId: EkoapiV1Transactions12870517_GET
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/client_ref_id:EKO20180219164433190:
    get:
      summary: EkoapiV1TransactionsClientRefIdEKO20180219164433190_GET
      description: Transaction Inquiry API using Partner reference number
      operationId: EkoapiV1TransactionsClientRefIdEKO20180219164433190_GET
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/16165313/refund:
    post:
      summary: EkoapiV1Transactions16165313Refund_POST
      description: Refund Transaction
      operationId: EkoapiV1Transactions16165313Refund_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}
  /ekoapi/v1/transactions/15065953/refund/otp:
    post:
      summary: EkoapiV1Transactions15065953RefundOtp_POST
      description: Resend Refund otp
      operationId: EkoapiV1Transactions15065953RefundOtp_POST
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}


  /ekoapi/v1/agent/user_code:20310003/settlementaccount:
    put:
      summary: EkoapiV1AgentUserCode20310003Settlementaccount_PUT
      description: Add bank account [Fund Settlement]
      operationId: EkoapiV1AgentUserCode20310003Settlementaccount_PUT
      tags:
        - AePS Fund Settlement
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
        - url: https://staging.eko.in:25004/
          variables: {}

  /ekoapi/v1/agent/user_code:20310003/settlementaccounts:
    get:
      summary: EkoapiV1AgentUserCode20310003Settlementaccounts_GET
      description: Get list of recipients mapped to user [Fund Settlement]
      operationId: EkoapiV1AgentUserCode20310003Settlementaccounts_GET
      tags:
        - AePS Fund Settlement
      parameters:
        - name: service_code
          in: query
          description: ''
          required: true
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            example: 39
        - name: Content-Type
          in: header
          description: ''
          required: true
          style: simple
          schema:
            type: string
            example: application/x-www-form-urlencoded
        - $ref: "#/components/parameters/initiator_id"
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}

  /ekoapi/v1/agent/user_code:20310003/settlement:
    post:
      summary: EkoapiV1AgentUserCode20310003Settlement_POST
      description: Initiate Settlement
      operationId: EkoapiV1AgentUserCode20310003Settlement_POST
      tags:
        - AePS Fund Settlement
      parameters:
        - $ref: "#/components/parameters/developer_key"
        - $ref: "#/components/parameters/secret-key"
        - $ref: "#/components/parameters/secret-key-timestamp"
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.in:25004/
        variables: {}


  /requestloan:
    post:
      summary: Requestloan_POST
      description: Request a loan
      operationId: Requestloan_POST
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
            example:
              ekoLoanHistory:
              - loanProviderName: Rupaiya Exchange
                loanAmount: 30000.0
                status: Acceptance In Review
              - loanProviderName: Happy Loans
                loanAmount: 50000.0
                status: Loan Disbursed Partially
              - loanProviderName: Mintifi
                loanAmount: 50000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Mintifi
                loanAmount: 50000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Rupaiya Exchange
                loanAmount: 30000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Mintifi
                loanAmount: 150000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Mintifi
                loanAmount: 100000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Rupaiya Exchange
                loanAmount: 120000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Mintifi
                loanAmount: 120000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Mintifi
                loanAmount: 100000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Mintifi
                loanAmount: 80000.0
                status: Loan Rejected By Merchant
              - loanProviderName: Rupaiya Exchange
                loanAmount: 80000.0
                status: Initiated
              isWeekendLoan: 0
              agent_code: 99040481
              loan_amount: 80000
              city: Pune City
              street: Smart Mobile 394 New Mangalwar Peth
              state: Maharashtra
              pincode: 411011
              firstName: Yogita
              lastName: Sudhir
              panNo: FLLPS1033N
              aadhaarNo: 484253598001
              dob: 1995-06-13
              mobileNo: 7066259607
              emailID: smartphone.xerox1@gmail.com
              agent_type: MERCHANT
              onboardedDate: 2017-05-25
              transactions:
              - transactionsType: Sales
                transactionsValue: 1316244.0
                transactionsMonthYear: 1/2018
                transactionsValueType: Volume
                primary: 0.0
              - transactionsType: Sales
                transactionsValue: 2088795.0
                transactionsMonthYear: 12/2017
                transactionsValueType: Volume
                primary: 0.0
              - transactionsType: Sales
                transactionsValue: 1418880.0
                transactionsMonthYear: 11/2017
                transactionsValueType: Volume
                primary: 0.0
              - transactionsType: Sales
                transactionsValue: 1288967.0
                transactionsMonthYear: 10/2017
                transactionsValueType: Volume
                primary: 0.0
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https:///<service_provider_base_url>/eko/
        variables: {}
  /create/evalue:
    put:
      summary: CreateEvalue_PUT
      description: Evalue request
      operationId: CreateEvalue_PUT
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request1'
            example:
              remarks: test
              date: 22022017
              bank_ref_num: 99872229222
              amount: 150000
              agent_code: 99021232
              source: Service Provider Name
              prefunder_bank: 1
              payment_mode: 4
              client_ref_id: 24774761487417892680
              bc: 1
              bank_code: HDFC
              loan_id: 429f2733-5b9f-40e6-9b22- fe642efb8aeb
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.co.in:25004/ekoicici/v1/loan/
        variables: {}
  /loanid:<product_id>:
    get:
      summary: LoanidProductId_GET
      description: Loan inquiry
      operationId: LoanidProductId_GET
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.co.in:25004/ekoicici/v1/loan/
        variables: {}
  /offerloan:
    post:
      summary: Offerloan_POST
      description: Loan callback
      operationId: Offerloan_POST
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request2'
            example:
              plan_id:
              product_id: 4e736c66-5032-7683-4b6d-697771584847
              step_num: 1
              proceed: true
              consumerId:
              claimed: false
              data:
                loanAmount: 100.0
                interestRate: 2.0
                interestType: percent
                repaymentDays:
                processingFees: 100.0
                loanType: ''
                tenure: 30
                additionalData: ''
                autoRepaymentStatus: 1
                expiryDate: 15-11-2017 21:00:00
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: http://test.webservices.eko.co.in:8080/ekoloanwebservice/webapi/<partner_code>/
        variables: {}
  /requestloan/accept:
    post:
      summary: RequestloanAccept_POST
      description: Accept a loan
      operationId: RequestloanAccept_POST
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request3'
            example:
              product_id: a1ef2e46-c2ed-4b0a-93bb-46954cb4f9a0
              step_num: 2
              data:
                consent:
                  customerAccept: true
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https:///<service_provider_base_url>/eko/
        variables: {}
  /repayment:
    post:
      summary: Repayment_POST
      description: Loan repayment
      operationId: Repayment_POST
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request4'
            example:
              loan_id: cbc27623-a0af-4838-9f8d-73a829183321
              disbursement_amount: 100000
              disbursement_date: 2017-02-24
              due_date: 2017-02-28
              repay_amount: 56565
              account_no: 22324234324
              reference_no: 2342423423
              sanction_id: fsdfsdfsdfsdfsf
              tranche_id: sdfsdfsdfsdferefsds
              source: 1
        required: true
      responses:
        200:
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://staging.eko.co.in:25004/ekoicici/v1/loan/
        variables: {}

## REUSABLE COMPONENTS...
components:
  parameters:
    initiator_id:
      $ref: components/parameters/initiator_id.yaml
    developer_key:
      $ref: components/parameters/developer_key.yaml
    secret-key:
      $ref: components/parameters/secret-key.yaml
    secret-key-timestamp:
      $ref: components/parameters/secret-key-timestamp.yaml
  schemas:
    Request:
      #$ref: components/schemas/Request.yaml
      title: Request
      required:
      - ekoLoanHistory
      - isWeekendLoan
      - agent_code
      - loan_amount
      - city
      - street
      - state
      - pincode
      - firstName
      - lastName
      - panNo
      - aadhaarNo
      - dob
      - mobileNo
      - emailID
      - agent_type
      - onboardedDate
      - transactions
      type: object
      properties:
          ekoLoanHistory:
              type: array
              items:
                  $ref: components/schemas/EkoLoanHistory.yaml
              description: ''
          isWeekendLoan:
              type: integer
              format: int32
          agent_code:
              type: string
          loan_amount:
              type: string
              example: 80000
          city:
              type: string
          street:
              type: string
          state:
              type: string
          pincode:
              type: string
          firstName:
              type: string
          lastName:
              type: string
          panNo:
              type: string
          aadhaarNo:
              type: string
          dob:
              type: string
          mobileNo:
              type: string
          emailID:
              type: string
          agent_type:
              type: string
          onboardedDate:
              type: string
          transactions:
              type: array
              items:
                  $ref: components/schemas/Transaction.yaml
              description: ''
      example:
        ekoLoanHistory:
        - loanProviderName: Rupaiya Exchange
          loanAmount: 30000.0
          status: Acceptance In Review
        - loanProviderName: Happy Loans
          loanAmount: 50000.0
          status: Loan Disbursed Partially
        - loanProviderName: Mintifi
          loanAmount: 50000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Mintifi
          loanAmount: 50000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Rupaiya Exchange
          loanAmount: 30000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Mintifi
          loanAmount: 150000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Mintifi
          loanAmount: 100000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Rupaiya Exchange
          loanAmount: 120000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Mintifi
          loanAmount: 120000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Mintifi
          loanAmount: 100000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Mintifi
          loanAmount: 80000.0
          status: Loan Rejected By Merchant
        - loanProviderName: Rupaiya Exchange
          loanAmount: 80000.0
          status: Initiated
        agent_code: 99040481
        loan_amount: 80000
        city: Pune City
        street: Smart Mobile 394 New Mangalwar Peth
        state: Maharashtra
        pincode: 411011
        firstName: Yogita
        lastName: Sudhir
        panNo: FLLPS1033N
        aadhaarNo: 484253598001
        dob: 1995-06-13
        mobileNo: 7066259607
        emailID: smartphone.xerox1@gmail.com
        agent_type: MERCHANT
        onboardedDate: 2017-05-25
        transactions:
        - transactionsType: Sales
          transactionsValue: 1316244.0
          transactionsMonthYear: 1/2018
          transactionsValueType: Volume
          primary: 0.0
        - transactionsType: Sales
          transactionsValue: 2088795.0
          transactionsMonthYear: 12/2017
          transactionsValueType: Volume
          primary: 0.0
        - transactionsType: Sales
          transactionsValue: 1418880.0
          transactionsMonthYear: 11/2017
          transactionsValueType: Volume
          primary: 0.0
        - transactionsType: Sales
          transactionsValue: 1288967.0
          transactionsMonthYear: 10/2017
          transactionsValueType: Volume
          primary: 0.0
    Request1:
      $ref: components/schemas/Request1.yaml
    Request2:
      $ref: components/schemas/Request2.yaml
    Request3:
      $ref: components/schemas/Request3.yaml
    Request4:
      $ref: components/schemas/Request4.yaml